### ISSUE TITLE
Implement subBytes() transformation

### ISSUE THREAD

**Issue by juniorz** [twstrike/AwESome#3]
I took some time to read the AES specification more carefully (and also check other explanations) and I think we were overlooking a few points:

Section 5.1.1 states that `subBytes(x)` is byte substitution which uses a substitution table known as Rijndael S-box which in turn is constructed by a composed transformation, having two parts:

1. take the multiplicative inverse of `x`
2. apply the affine transformation on the multiplicative inverse of `x`

That's why we failed to calculate the S-box on the paper today - we were ignoring the first step and applying the affine transformation directly to `x`.

Section 4.2 specify how to take the multiplicative inverse of b(x) (in the finite field GF(2^8)) which essentially is to use the extended Euclidean algorithm to compute polynomials a(x) and c(x) such that b(x)a(x) + m(x)c(x) = 1. And the extended Euclidean algorithm is another problem on itself.

All this to generate the Rijndael S-box. Do you think it's worth going over all this trouble just to generate the table since its included in the specification?

Anyway, I found very interesting explanations of both steps (including the extended Euclidean algorithm in the finite field GF(2^8) ) and I'm planning to go over them on paper tomorrow.

References:
What are elements of this finite field GF(2^8)?
http://mathforum.org/library/drmath/view/66982.html

How to use the extended Euclidean algorithm in GF(2^8) with an arbitrary irreducible polynomial f(x)?
http://mathforum.org/library/drmath/view/51675.html
Note AES has its own choice for the irreducible polynomial (also in section 4.2).

The Rijndael S-box and step-by-step instructions on how to generate it
https://en.wikipedia.org/wiki/Rijndael_S-box and http://crypto.stackexchange.com/questions/10996/how-are-the-aes-s-boxes-calculated

cc/ @tcz001

**Comment by tcz001** [comment]
Nice investigation, we should not ignore the inverse, my bad.
2015年6月17日 下午11:59于 Reinaldo de Souza Junior <notifications@github.com>写道：I took some time to read the AES specification more carefully (and also check other explanations) and I think we were overlooking a few points:

Section 5.1.1 states that subBytes(x) is byte substitution which uses a substitution table known as Rijndael S-box which in turn is constructed by a composed transformation, having two parts:

take the multiplicative inverse of x
apply the affine transformation on the multiplicative inverse of x


That's why we failed to calculate the S-box on the paper today - we were ignoring the first step and applying the affine transformation directly to x.

Section 4.2 specify how to take the multiplicative inverse of b(x) (in the finite field GF(2^8)) which essentially is to use the extended Euclidean algorithm to compute polynomials a(x) and c(x) such that b(x)a(x) + m(x)c(x) = 1. And the extended Euclidean algorithm is another problem on itself.

All this to generate the Rijndael S-box. Do you think it's worth going over all this trouble just to generate the table since its included in the specification?

Anyway, I found very interesting explanations of both steps (including the extended Euclidean algorithm in the finite field GF(2^8) ) and I'm planning to go over them on paper tomorrow.

References:
What are elements of this finite field GF(2^8)?
http://mathforum.org/library/drmath/view/66982.html

How to use the extended Euclidean algorithm in GF(2^8) with an arbitrary irreducible polynomial f(x)?
http://mathforum.org/library/drmath/view/51675.html
Note AES has its own choice for the irreducible polynomial (also in section 4.2).

The Rijndael S-box and step-by-step instructions on how to generate it
https://en.wikipedia.org/wiki/Rijndael_S-box and http://crypto.stackexchange.com/questions/10996/how-are-the-aes-s-boxes-calculated

cc/ @tcz001
